### ISSUE TITLE
Support for Swift Package Manager and Xcode 11

### ISSUE THREAD

**Issue by mackoj** [optimizely/swift-sdk#223]
Can you please consider fixing your Package.swift in order to support Xcode 11 ?

**Comment by thomaszurkan-optimizely** [comment]
@mackoj Thanks for the feedback.  We will definitely add package manager support so that Xcode 11 doesn't have any problems.  Let us know if there is any other feedback.

**Comment by thomaszurkan-optimizely** [comment]
@mackoj .  We have support for swift packages.
