### ISSUE TITLE
SSL Pinning for events endpoint.

### ISSUE THREAD

**Issue by thomaszurkan-optimizely** [optimizely/swift-sdk#240]

**Comment by mikeng13** [comment]
Decided not to support.

**Comment by EvgenyKarkan** [comment]
Hello @thomaszurkan-optimizely 

I’m wondering if SSL pinning is applied selectively then?, particularly for the `/datafiles` endpoint. 
Could you please confirm whether it is implemented or not?

**Comment by jaeopt** [comment]
@EvgenyKarkan we do not support SSL pinning in the SDK.

**Comment by EvgenyKarkan** [comment]
@jaeopt got it, thanks for a quick reply!
