### ISSUE TITLE
Request: Make project config public to consumers of the SDK

### ISSUE THREAD

**Issue by Killectro** [optimizely/swift-sdk#261]
In the Objective C version of the SDK we are able to grab the values of all currently-running experiments in order to pass that data to our internal analytics services. We use something like this to grab a dictionary of all experiments and the variation the user falls into for each experiment:

```swift
let experimentKeysAndVariations = client
    .optimizely?
    .config?
    .allExperiments?
    .compactMap { experiment in
        client.variation(
            experiment.experimentKey,
            userId: optimizelyUserID(),
            attributes: optimizelyAttributes()
        ).map { variation in
            (experiment.experimentKey, variation.variationKey)
        }
    } ?? []

return Dictionary(experimentKeysAndVariations, uniquingKeysWith: { _, new in new })
```

In the Swift SDK we are unable to do this because `OptimizelyClient`'s config is marked as `internal`.

Is it possible to expose the `ProjectConfig` publicly? This seems to be the last thing preventing us from upgrading to the Swift SDK. We really want access to datafile update notifications, but we can't until we figure out this last piece of the puzzle.

Cheers

**Comment by khaptonstall** [comment]
In the same boat here. @thomaszurkan-optimizely @jaeopt this seems like a reasonably small update to the SDK to allow a more seamless transition from the Objective SDK to Swift. Is it possible to get these properties publicly exposed and release a new version soon?

**Comment by jaeopt** [comment]
We're currently working on extending our API to access those project data in a controlled way. A revision with the fix will be released soon.

**Comment by khaptonstall** [comment]
@thomaszurkan-optimizely @jaeopt 

Any update on this? Or is it possible to get a more concrete estimate of what "soon" is?

**Comment by jaeopt** [comment]
@khaptonstall Its design and implementation completed and under testing. We expect it'll be released in a couple weeks, can be a little earlier or later.

**Comment by khaptonstall** [comment]
@jaeopt Awesome, thanks for the update!

**Comment by jaeopt** [comment]
@Killectro @khaptonstall Swift SDK rev 3.2.1 has been released with a new API (OptimizelyConfig) to access project configuration data. Check it out and let us know if you have any issues or feedback.
