### ISSUE TITLE
Request: Enable "Allow app extension API only" in OptimizelySwiftSDK-iOS

### ISSUE THREAD

**Issue by denysco** [optimizely/swift-sdk#276]
We're in process of switching from objc to swift SDK. obj-c SDK for iOS has checked Allow app extension API only, but Swift SDK isn't. We need to use Optimizely in app extension safe frameworks.
Would it be possible to make swift SDK extension safe?
Thanks!

**Comment by jaeopt** [comment]
It'll be fixed as requested. Thanks

**Comment by jaeopt** [comment]
@denysco Swift SDK rev 3.2.1 released with this fix included. Check it out!
