### ISSUE TITLE
More Logging Info

### ISSUE THREAD

**Issue by gal-orlanczyk** [optimizely/swift-sdk#362]
The logs are great but they include all the data as one string which makes it hard to use for dashboards and handle data later on.
For example it would have been great to receive object instead of string message:

```
[
    "message" : "feature (1120) ...."
    "feature" : "1120"
    "isEnabled": true
]
```

isEnabled and such are optionals just a suggestion. 
The main thing I would really appreciate to have is the feature key.
This help me identify specific features logs easily.

**Comment by jaeopt** [comment]
Thanks for your input. We're actually working on improving the decision result more aligned with what you requested.

**Comment by gal-orlanczyk** [comment]
Awesome!!! is there an approximate date for release?

**Comment by jaeopt** [comment]
This detailed log info in DecisionReason is supported in the new "decide" APIs.
