### ISSUE TITLE
Crash when using multiple Optimizely clients with custom logger

### ISSUE THREAD

**Issue by gal-orlanczyk** [optimizely/swift-sdk#364]
Hi, I have discovered a super crazy bug when initializing multiple instances crashes the app, and it always failed in: `registerServices` long story short, I have found that providing the init with logger for more than one instance causes this.
Only when providing one single Optimizely client with a logger the factory knows how to resolve the same instance for all if there are more than one, it crashes... I would expect the behavior to be to override the instance...

**Comment by thomaszurkan-optimizely** [comment]
@gal-orlanczyk can you provide your custom logger implementation?  and, how you are instantiating multiple instances?  for instance, we don't support multiple clients with the same sdk key.  Thanks.

**Comment by gal-orlanczyk** [comment]
@thomaszurkan-optimizely the logger implementation is super simple and just pass everything to our own logger nothing there.
When I initialize a second client with the same sdk key it crashes.

It is weird you say this as one of your support engineers we consulted with recommend this as a possible solution to our problem, and he mentioned he met many companies using even 3-6 clients together.

**Comment by jaeopt** [comment]
SDK 3.8.0 has been released, which includes a full support for multiple clients (sdkKeys).
This will be closed. Let us know if you see the issue again.
