### ISSUE TITLE
Remove the getter from AtomicProperty

### ISSUE THREAD

**Issue by ericcole-nike** [optimizely/swift-sdk#382]
The getter on AtomicProperty only protects the reference when T is a reference type and is completely unsafe when T is a hidden reference type like Array or Dictionary.

These are totally unsafe and causing crashes:
DefaultDatafileHandler.timers
HandlerRegistryService.binders

These are misused and basically defeat the purpose of an atomic object:
OptimizelyClient.atomicConfig
DefaultEventDispatcher.timer

Remove the getter and add methods like these to AtomicProperty:

```
    public func modify(_ handler: @escaping (inout T?) -> Void) {
        lock.async(flags: .barrier) {
            handler(&self._property)
        }
    }

    public func access(_ handler: @escaping (T?) -> Void) {
        lock.async {
            handler(self._property)
        }
    }

    public func access<R>(_ handler: (T?) throws -> R) rethrows -> R {
        return try lock.sync {
            return try handler(self._property)
        }
    }

```

Then create a subclass for use with DefaultDatafileHandler.timers and HandlerRegistryService.binders:

```
public class AtomicDictionary<Key: Hashable, Value>: AtomicProperty<Dictionary<Key, Value>> {
    public var count: Int { return access { $0.count } }

    public subscript(_ key: Key) -> Value? {
        get { return access { $0[key] } }
        set { modify { $0[key] = newValue } }
    }

    public func removeAll() { modify { $0.removeAll() } }
}
```

**Comment by thomaszurkan-optimizely** [comment]
@ericcole-nike, can you provide more details on any crashes?  I have thought about changing those to use the performAtomic which handles the modify.  When modifying an array accessing like atomic.property[offset] = value, it calls both a get and set. 
Are you saying it is assigning to a local variable and modifying?  Thanks for your input.

**Comment by ericcole-nike** [comment]
Yes, atomic.property[offset] = value is really

var p = atomic.property
p[offset] = value
atomic.property = p

Since dictionaries and arrays do a magic copy-on-write thing, both of those local p instances are referring to the same mutable data structure, and both may copy or modify it as they see fit, outside the protection of the dispatch queue.

This is a crash that we’re seeing.  Looking down a few levels, the AtomicProperty was used to access the logger instance.

[cid:1484C84D-772E-425D-B1C9-CE21E9E01638@hsd1.or.comcast.net.]

On Jan 26, 2021, at 10:47 AM, Tom Zurkan <notifications@github.com<mailto:notifications@github.com>> wrote:



@ericcole-nike<https://urldefense.com/v3/__https://github.com/ericcole-nike__;!!KLCbKzk!zom4i8n1CE6lUkk-EDli71Q8N1hxQFqO5RDfGpbASwJJjklw-7JjDlawZzyGAw$>, can you provide more details on any crashes? I have thought about changing those to use the performAtomic which handles the modify. When modifying an array accessing like atomic.property[offset] = value, it calls both a get and set.
Are you saying it is assigning to a local variable and modifying? Thanks for your input.

**Comment by thomaszurkan-optimizely** [comment]
@ericcole-nike  The logger factory is the only thing that is wrapped in an atomic property.  The logger is on a per instance bases and is not shared.  The logger is lazy loaded.  In the crash I did see, the problem definitely has nothing to do with atomic property as logger is loaded in optimizely client init.  The problem may be that the logger needs to be atomic as some components (such as datafile handler) are multi-threaded.

**Comment by ericcole-nike** [comment]
Our custom logger is a thin wrapper around our main logging system.  NTC.log.logMessage takes an escaping closure and runs it asynchronously on a separate queue.


    private final class Logger: OPTLogger {
        static var logLevel: OptimizelyLogLevel = .verbose

        required init() {}

        func log(level: OptimizelyLogLevel, message: String) {
            guard level.rawValue <= Logger.logLevel.rawValue else { return }

            let message = "🛢 " + message
            let logLevel: Willow.LogLevel

            switch level {
            case .off, .error:            logLevel = .error
            case .warning:                logLevel = .warn
            case .info:                   logLevel = .info
            case .debug, .verbose:        logLevel = .debug
            @unknown default:             logLevel = .debug
            }

            NTC.log.logMessage({ message }, with: logLevel)
        }
    }


On Jan 27, 2021, at 9:34 AM, Tom Zurkan <notifications@github.com<mailto:notifications@github.com>> wrote:



@ericcole-nike<https://urldefense.com/v3/__https://github.com/ericcole-nike__;!!KLCbKzk!ys6_oD26rtu1QjuP_mtFOU-tt8Rm0JLqyI_DVJC-K5mrOm2kLXcYYLEb6cHWiA$> The logger factory is the only thing that is wrapped in an atomic property. The logger is on a per instance bases and is not shared. The logger is lazy loaded. In the crash I did see, the problem definitely has nothing to do with atomic property as logger is loaded in optimizely client init. The problem may be that the logger needs to be atomic as some components (such as datafile handler) are multi-threaded.

**Comment by AnthonyOliveri** [comment]
I seem to be experiencing a similar issue. The app occasionally crashes when calling the OptimizelyClient `getAllFeatureVariables` method (occurs in production, but not reproducible locally). This is with version v3.7.0 of the SDK.

<img width="729" alt="Screen Shot 2021-05-04 at 10 45 50 AM" src="https://user-images.githubusercontent.com/5459406/117031999-bed40480-acc6-11eb-87f0-a3b0322e6ee7.png">

**Comment by jaeopt** [comment]
@AnthonyOliveri Thanks for sharing. We'll look into it.

**Comment by jaeopt** [comment]
SDK 3.8.0 has been released, which includes a full support for multiple clients (sdkKeys) and this thread issue.
This will be closed. Let us know if you see it again.
