### ISSUE TITLE
Add support for watchOS

### ISSUE THREAD

**Issue by daltonclaybrook** [optimizely/swift-sdk#388]
We need the ability to use the Optimizely SDK from a watchOS app. It appears that this is not currently possible. This should hopefully be a fairly straightforward change considering many of the same Swift/Foundation APIs are available for both iOS and watchOS.

**Comment by jaeopt** [comment]
@daltonclaybrook We'll take a look. Any size limitation? Our SDK currently about 800KB (400KB compressed).

**Comment by daltonclaybrook** [comment]
I think that should be fine. I believe the current size limit for watchOS apps is 75 MB.
