### ISSUE TITLE
Add macCatalyst Support

### ISSUE THREAD

**Issue by mrcperello** [optimizely/swift-sdk#389]
We would like to use Optimisely Framework from a macCatalyst app. This appears to not be supported. It should be pretty straightforward since the framework already supports iOS and macOS.

**Comment by jaeopt** [comment]
@mrcperello We looked into support for macCatalyst. It looks like our swift-sdk will work as is. Let me know if you find any issue when using it for catalyst. One key difference is that DidEnterBackgroundNotification won't be fired for macCatalyst apps. It's the design by Apple and there should be no issue.
