### ISSUE TITLE
Fix build warning please

### ISSUE THREAD

**Issue by VonoPTS** [optimizely/swift-sdk#393]
Hi, Optimizely team! I'm about to upgrade the SDK from version 3.6.1 to version 3.7.0 but there is problem. I use SPM as a dependency manager and Swiftlint as a linter for my project, on CI side my builds are red due to:

File `OptimizelyClient+Extension.swift` line 28:
`var binder: Binder = Binder<OPTLogger>(service: OPTLogger.self, factory: type(of: logger).init)`
variable 'binder' was never mutated; consider changing to 'let' constant 

May I ask you to fix it?

**Comment by jaeopt** [comment]
@VonoPTS Thanks for sharing this. We'll fix it in the next release. Let us know if you have a workaround for now.

**Comment by jaeopt** [comment]
@VonoPTS This issue and other lint warnings have been fixed and will be included in the next release.
