### ISSUE TITLE
SPM - "swift-sdk" causes package name conflicts

### ISSUE THREAD

**Issue by mrtnrst** [optimizely/swift-sdk#450]
## Overview
The way SPM imports happen uses the "repo name." Because of this, anyone importing this package, at any point, will conflict with other similarly named packages. Unsure of the correct course of action here, as this package is undoubtedly included in plenty of different projects.

I'll create this issue on Iterable (the other repo that initially caused this to show up) and link and tag to see if there can be a consensus on the outcome.

EDIT: Linking Iterable issue Iterable/swift-sdk#537

### Example Project
I haven't made an example project, but you can recreate this issue by creating a blank project and adding both this SDK and the [Iterable/swift-sdk](https://github.com/Iterable/swift-sdk) SDK.

### Workarounds
Currently, the only workaround I have found is forking the package in a separate repo to rename the repo and going from `swift-sdk` to `optimizely-swift-sdk`.

**Comment by jaeopt** [comment]
@mrtnrst Thanks for reporting. We'll take a look.

**Comment by jaeopt** [comment]
@mrtnrst It looks like a bug in Xcode. There can be many swift packages which can share the last part of unique urls (swift-sdk, ios-sdk, etc) and Xcode is supposed to use the url (or package name) as a reference. We filed a bug report to Apple. Interestingly, you're the first user who had this issue with multiple SDKs with the same names :)

**Comment by mrtnrst** [comment]
@jaeopt looks like this is resolved in Xcode 13.3 as SPM updated to version 2 file format. I'll go ahead and close this ticket. Thanks for taking a look!

![SpongeBob squarepants thank you](https://media3.giphy.com/media/6tHy8UAbv3zgs/giphy.gif)

**Comment by mrtnrst** [comment]
Welp, I spoke too soon. After a clean/build it's failing again.
<img width="1081" alt="image" src="https://user-images.githubusercontent.com/1743953/159042294-731c1003-ce72-4865-85b9-f03b3930422e.png">

**Comment by jaeopt** [comment]
@mrtnrst We created an aliased repo: "https://github.com/optimizely/optimizely-swift-sdk.git", same as the original one but you can use to manage the xcode name conflict. Let us know if you see any issue with the solution. Tx.

```
If you have a name conflict with other swift packages when you add the Optimizely swift-sdk dependency to Xcode, you can also try with its aliased repo: "https://github.com/optimizely/optimizely-swift-sdk.git"
```
