### ISSUE TITLE
Inconsistent data polling update intervals

### ISSUE THREAD

**Issue by ifnull** [optimizely/swift-sdk#469]
We have configure datafile polling at 15 minute intervals and are using a bundled datafile. However we are seeing the polling firing between 15 and 30 minutes. We have noticed this issue does not occur when lowering the polling interval to 5 minutes. Are there any known limitations or issues with polling?

**Comment by jaeopt** [comment]
@ifnull Thanks for sharing the issue. We'll take a look. 
Datafile polling works only while app runs foreground. Is your app running foreground for a long time (more than 15mins)?

**Comment by ifnull** [comment]
Thanks for the response. We initially suspected that the issue was caused by the app being in the background, however subsequent tests were done with the app open and in the foreground with the same result.

**Comment by Tamara-Barum** [comment]
Internal Ticket for tracking: [FSSDK-8674]

**Comment by jaeopt** [comment]
@ifnull there is no limitations on the interval value, so 5min and 15min not supposed to make difference in behavior. I believe the time drift you observe is from iOS control of when to fire the timer event depending on device load, app state (suspended/background/foreground).

**Comment by jaeopt** [comment]
@ifnull this will be closed for now. Let us know to open it again if you see any further issues regarding the topic.
