### ISSUE TITLE
Any plan to support SPM binaryTarget

### ISSUE THREAD

**Issue by bluepi0j** [optimizely/swift-sdk#478]
Do you have any plan to support SPM binaryTarget? Like what https://github.com/airbnb/lottie-spm Lottie do or Facebook sdk https://github.com/facebook/facebook-ios-sdk/blob/main/Package.swift do. It can download quicker and reduce build time

**Comment by jaeopt** [comment]
@bluepi0j swift is now binary compatible, so it may be a good time for that. We'll look into it.

**Comment by russell-loube-optimizely** [comment]
Hi @bluepi0j , we have reviewed this as a team and have added a research ticket to our backlog. We unfortunately don't have a timeline for when we'd look at this at the moment. We'll respond here when we have an update on prioritization. Thanks.

**Comment by russell-loube-optimizely** [comment]
For your reference:

- FSS-I-325 (feedback.optimizely.com ticket number)
- FSSDK-9122 (internal Jira ticket number)
