### ISSUE TITLE
.ignoreUserProfileService is missing in DefaultDecisionService

### ISSUE THREAD

**Issue by ginesnf** [optimizely/swift-sdk#509]
Hi, 

I want to use the **.ignoreUserProfileService** policy but following the code I can see that **decisionService.getVariation** call in **OptimizelyClient** class has nil options and not **defaultDecideOptions**

https://github.com/optimizely/swift-sdk/blob/193cc00e1004d29f16f7b32e5b6787199760c482/Sources/Optimizely/OptimizelyClient.swift#L304

In **DefaultDecisionService** there is a check for this policy but **options** always will be nill
https://github.com/optimizely/swift-sdk/blob/193cc00e1004d29f16f7b32e5b6787199760c482/Sources/Implementation/DefaultDecisionService.swift#L89

Is it correct?

Thanks.

**Comment by Tamara-Barum** [comment]
Ticket created for internal review: FSSDK-9404

**Comment by ginesnf** [comment]
Thanks for your answer @jaeopt,

We cloned the repository and modified those "nils" to add the `defaultDecideOptions` and it works perfectly. Our code is also legacy and depend a lot of your legacy code. For that, why we want to know if a fix is possible for your side. 

Thanks.

**Comment by jaeopt** [comment]
@ginesnf glad to hear that you found a workaround. No plan to add the options to the legacy apis. You can consider migrating to decide apis. Most apis one-to-one mapped, migrating should be straightforward - https://docs.developers.optimizely.com/feature-experimentation/docs/migrate-from-older-versions-swift
