### ISSUE TITLE
Several questions

### ISSUE THREAD

**Issue by twittemb** [optimizely/swift-sdk#510]
Hi there.

Here is a list of questions regarding the Swift SDK:

- in async mode, the documentation says in case of network issue it will fallback to the cache file and then to the bundled file. I cannot see a constructor for the async mode that takes the bundled file as a parameter. Am I missing something ?
- do you plan to support Swift concurrency ? (an adaptation layer is easy to implement on the client side though)
- is there a way to deactivate the impression sending for every decisions at once ?

Thanks for your answers.

**Comment by Tamara-Barum** [comment]
An internal ticket has been created to review these questions:FSSDK-9405

**Comment by jaeopt** [comment]
> * in async mode, the documentation says in case of network issue it will fallback to the cache file and then to the bundled file. I cannot see a constructor for the async mode that takes the bundled file as a parameter. Am I missing something ?

The fallback datafile is not supported in the async mode of the swift-sdk. It's for sync mode only. 

> * do you plan to support Swift concurrency ? (an adaptation layer is easy to implement on the client side though)

Yes, we plan to add the concurrency version of our async apis.

> * is there a way to deactivate the impression sending for every decisions at once ?

If you use our `decide` api, you can disable it with `OptimizelyDecideOption.disableDecisionEvent`. It can be set for all decisions as default decide option when the SDK is initialized, or can be also controlled for each decide call as well.

**Comment by twittemb** [comment]
Thanks a lot for the answers.

About the async initialisation I guess the documentation is misleading then (https://docs.developers.optimizely.com/feature-experimentation/docs/initialize-sdk-swift#asynchronous-initialization) because it explicitly says that the fallback is the cached filed and then the bundled file.

About async/await, do you have an ETA ?

**Comment by jaeopt** [comment]
> About the async initialisation I guess the documentation is misleading then (https://docs.developers.optimizely.com/feature-experimentation/docs/initialize-sdk-swift#asynchronous-initialization) because it explicitly says that the fallback is the cached filed and then the bundled file.

Correct. It'll be fixed.

> About async/await, do you have an ETA ?

Probably sometime in Q3.

**Comment by basselalesh** [comment]
Hey, is this fix still on the roadmap? Async initialization with a bundled datafile fallback?

**Comment by jaeopt** [comment]
@basselalesh we do not have a plan to add "bundled datafile fallback" to async init. It's a doc error. The doc will be fixed to be consistent. The bundled datafile is only for the first time app starts after installing. It's not likely that datafile fallback is needed after app is installed successfully.
