### ISSUE TITLE
[BUG] Upload Task Request contains Body

### ISSUE THREAD

**Issue by michaeldclifford** [optimizely/swift-sdk#519]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SDK Version

3.10.2

### iOS Version

17.0

### Current Behavior

When running an App with the Optimizely SDK integrated, the following error message is shown in Xcode 15:

> The request of a upload task should not contain a body or a body stream, use `upload(for:fromFile:)`, `upload(for:from:)`, or supply the body stream through the `urlSession(_:needNewBodyStreamForTask:)` delegate method.
> _[DefaultEventDispatcher.swift > L184-L192](https://github.com/optimizely/swift-sdk/blob/master/Sources/Customization/DefaultEventDispatcher.swift#L184-L192)_

### Expected Behavior

The SDK should not have any runtime issues flagged by Xcode

### Steps To Reproduce

Run an App that has the Optimizely SDK integrated and calls [`sendEvent(event: EventForDispatch, completionHandler: @escaping DispatchCompletionHandler)`](https://github.com/optimizely/swift-sdk/blob/master/Sources/Customization/DefaultEventDispatcher.swift#L173)

### Link

[`sendEvent(event: EventForDispatch, completionHandler: @escaping DispatchCompletionHandler)`](https://github.com/optimizely/swift-sdk/blob/master/Sources/Customization/DefaultEventDispatcher.swift#L173)

### Logs / Stacktraces

```
- DefaultEventDispatcher.flushEvents(), L151
  - self.sendEvent(event:completionHandler:), L192
```

**Comment by muzahidul-opti** [comment]
acknowledged

**Comment by muzahidul-opti** [comment]
Hi @michaeldclifford, thank you for your patience. The issue has been resolved. Please check out our latest release.
