### ISSUE TITLE
[ENHANCEMENT] SPM Integration

### ISSUE THREAD

**Issue by delannoyk** [optimizely/swift-sdk#520]
### Description

Hi Optimizely team,

We're in the process of integrating another SDK in our app using SPM and unfortunately, we can't. The reason is that the name of this repository is `swift-sdk` and one of our other dependencies is also using `swift-sdk`.

> dependency on 'https://github.com/iterable/swift-sdk' conflicts with dependency on 'https://github.com/optimizely/swift-sdk' which has the same identity 'swift-sdk'

After digging a little bit, I found that I was not the only one having this issue (thread [here](https://forums.swift.org/t/two-third-party-packages-share-the-same-name/60721))

According to official SPM team members:
> SwiftPM uses the last path component of URL as the "identity";

I tried using `SSH` instead of `https` but it didn't help.

### Benefits

Be able to use SPM

**Comment by jaeopt** [comment]
@delannoyk you can integrate our sdk with this alias https://github.com/optimizely/optimizely-swift-sdk.git which we support for the name conflict. See https://github.com/optimizely/swift-sdk/issues/450 for more details.

**Comment by delannoyk** [comment]
@jaeopt Thank you so much for the prompt response. I'll give this a try!
