### ISSUE TITLE
[BUG] Incorrect value inside the Privacy manifest file

### ISSUE THREAD

**Issue by Faber92** [optimizely/swift-sdk#538]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### SDK Version

3.10.4

### iOS Version

Any

### Current Behavior

The used value `To store configuration and event data temporarily` for `NSPrivacyAccessedAPITypeReasons` is not compliant with the [requirements](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api#4278401) by Apple 

```
<key>NSPrivacyAccessedAPITypeReasons</key>
<array>
<string>To store configuration and event data temporarily</string>
</array>
```

### Expected Behavior

I expect to see one of the following values as listed [here](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api#4278401):
- CA92.1
- 1C8F.1
- C56D.1
- AC6B.1

### Steps To Reproduce

None

### Severity

Minor issue

**Comment by muzahidul-opti** [comment]
Hi @Faber92 thanks for reporting the issue. Will get back to you.
