### ISSUE TITLE
[ENHANCEMENT] Cocoapods support for privacy manifest

### ISSUE THREAD

**Issue by Faber92** [optimizely/swift-sdk#539]
### Description

Listing the `PrivacyInfo.xcprivacy` file inside the `resource_bundles` specification in the podspec allows to distribute the file correctly. Ref. [CocoaPods#10325](https://github.com/CocoaPods/CocoaPods/issues/10325#issuecomment-1718723762)

### Benefits

It will help users who integrate the SDK via CocoaPods to be compliant with Apple's updated privacy requirements.

**Comment by muzahidul-opti** [comment]
@Faber92 Issue is fixed in our latest release.
