### ISSUE TITLE
[ENHANCEMENT] visionOS Support

### ISSUE THREAD

**Issue by loganblevins** [optimizely/swift-sdk#550]
### Description

Would like visionOS support

### Benefits

Continued use as a customer on a new platform and not seeking competitors.

**Comment by muzahidul-opti** [comment]
@loganblevins really appreciated your concern. Supporting visionOS would be nice. Can you please drop your feedback [here](https://feedback.optimizely.com/ideas)?

**Comment by loganblevins** [comment]
@muzahidul-opti I tried logging in there but was unable... is this login info my standard Optimizely credentials?

**Comment by loganblevins** [comment]
@muzahidul-opti It's not working. I have an optimizely account I use daily but it won't let me login on that feedback site.
<img width="365" alt="Screenshot 2024-02-08 at 12 15 59" src="https://github.com/optimizely/swift-sdk/assets/12498682/e125bd74-6789-489d-ad62-c5ef9d53df06">

**Comment by loganblevins** [comment]
I had to make a new account on that site. Feedback submitted: FSS-I-358 .

Do you know when this may be supported? @muzahidul-opti

**Comment by muzahidul-opti** [comment]
With the feedback submitted, we will bring up with product, discuss prioritization, and get back to you with an estimate after that conversation. 

If you don't mind, I'm going to close the issue from here.
